# Generated by Django 4.1.4 on 2023-06-22 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17)])),
                ('class_level', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=3)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('marklist', models.FileField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
