# Generated by Django 4.1.4 on 2023-06-22 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0002_studentdb_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(17)])),
                ('class_level', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th')], max_length=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('marklist', models.FileField(upload_to='marklist/')),
            ],
        ),
        migrations.DeleteModel(
            name='Studentdb',
        ),
    ]
